DROP TRIGGER IF EXISTS UPDATE_LOAN_DETAILS_TIMESTAMP ON LOAN_DETAILS;

DROP INDEX IF EXISTS IDX_LOAN_DETAILS_LOAN_DATE;

DROP INDEX IF EXISTS IDX_LOAN_DETAILS_RETURN_DATE;

DROP INDEX IF EXISTS IDX_LOAN_DETAILS_BOOK_ID;

DROP INDEX IF EXISTS IDX_LOAN_DETAILS_RETURNED_ON;

ALTER TABLE LOAN_DETAILS
DROP CONSTRAINT IF EXISTS FK_LOAN_DETAILS_BOOK;

DROP TABLE IF EXISTS LOAN_DETAILS;